import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

export function Footer() {
  return <footer className="site-footer mt-20 border-t border-white/10 bg-[#09090b] text-white"><div className="shell">
    <div className="flex flex-wrap items-end justify-between gap-6 border-b border-white/15 py-10"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] opacity-60">Следующий шаг</p><h2 className="mt-2 max-w-xl text-2xl font-extrabold sm:text-3xl">Найдите роль, которая подходит не только по названию.</h2></div><Link href="/professions" className="inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 font-extrabold text-[#111113] transition hover:-translate-y-1 hover:bg-[#f1f1f1]">Открыть каталог <ArrowUpRight size={17} /></Link></div>
    <div className="grid gap-8 py-10 text-sm opacity-80 md:grid-cols-[1.4fr_1fr_1fr]"><div><p className="font-extrabold opacity-100">TechRole <span className="text-accent">Index</span></p><p className="mt-2 max-w-md leading-6">Прозрачная аналитика IT-профессий. Каждый показатель сопровождается периодом, размером выборки и описанием методики расчёта.</p></div>
      <div className="grid content-start gap-2"><Link className="hover:opacity-60" href="/research">Исследование рынка</Link><Link className="hover:opacity-60" href="/insights">Разборы данных</Link><Link className="hover:opacity-60" href="/reports/weekly">Еженедельный отчёт</Link><Link className="hover:opacity-60" href="/feed.xml">RSS-дайджест</Link><Link className="hover:opacity-60" href="/data-status">Статус данных</Link><Link className="hover:opacity-60" href="/salary-benchmarks">Зарплатный датасет</Link><Link className="hover:opacity-60" href="/open-data-daily">Ежедневный датасет</Link><Link className="hover:opacity-60" href="/methodology">Методология</Link><Link className="hover:opacity-60" href="/glossary">Глоссарий</Link><Link className="hover:opacity-60" href="/sources">Источники</Link><Link className="hover:opacity-60" href="/citation">Как цитировать</Link><Link className="hover:opacity-60" href="/about">О проекте</Link><Link className="hover:opacity-60" href="/status">Статус сервиса</Link><Link className="hover:opacity-60" href="/support">Техподдержка</Link></div>
      <div className="grid content-start gap-2"><Link className="hover:opacity-60" href="/mentorship">Личное ведение</Link><Link className="hover:opacity-60" href="/pricing">Тарифы</Link><Link className="hover:opacity-60" href="/dashboard">Дашборд</Link><Link className="hover:opacity-60" href="/legal/offer">Публичная оферта</Link><Link className="hover:opacity-60" href="/legal/refunds">Возвраты</Link><Link className="hover:opacity-60" href="/legal/privacy">Обработка данных</Link><Link className="hover:opacity-60" href="/legal/consent">Согласия</Link></div>
    </div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/15 py-5 text-xs opacity-65"><span>© 2026 TechRole Index</span><span className="inline-flex items-center gap-2"><span className="live-dot" /> Расчёты выполняются по расписанию</span></div>
  </div></footer>;
}
