import os

os.environ.update(
    {
        "APP_ENV": "test",
        "APP_SECRET_KEY": "test-secret-key-with-enough-entropy",
        "DATABASE_URL": "sqlite:///./test-techrole.sqlite3",
        "FRONTEND_ORIGIN": "http://localhost:3000",
        "PUBLIC_BASE_URL": "http://localhost:3000",
        "CATALOG_CACHE_ENABLED": "false",
        "AI_CLASSIFIER_ENABLED": "false",
        "HH_ENABLED": "false",
        "TRUDVSEM_ENABLED": "false",
        "CBR_CURRENCY_ENABLED": "false",
        "SUPPORT_EMAIL_ENABLED": "false",
        "NIGHTLY_REPORT_EMAIL_ENABLED": "false",
        "ANALYTICS_ENABLED": "false",
        "ANALYTICS_INGEST_KEY": "",
        "ANALYTICS_HASH_KEY": "",
        "PAYMENTS_ENABLED": "false",
        "PAYMENTS_PROVIDER": "demo",
        "PAYMENTS_MODE": "test",
        "PAYMENTS_LIVE_CONFIRMED": "false",
        "PAYMENTS_LEGAL_APPROVED": "false",
        "PAYMENTS_STABLE_HTTPS_CONFIRMED": "false",
        "PAYMENTS_TERMS_VERSION": "draft-test",
        "PAYMENTS_SELLER_STATUS": "unconfirmed",
        "PAYMENTS_FISCALIZATION_MODE": "disabled",
        "PAYMENTS_ROBOCHEKI_SMZ_CONFIRMED": "false",
        "ROBOKASSA_MERCHANT_LOGIN": "",
        "ROBOKASSA_PASSWORD1": "",
        "ROBOKASSA_PASSWORD2": "",
        "ROBOKASSA_TEST_PASSWORD1": "",
        "ROBOKASSA_TEST_PASSWORD2": "",
        "ROBOKASSA_LIVE_PASSWORD1": "",
        "ROBOKASSA_LIVE_PASSWORD2": "",
        "ROBOKASSA_LIVE_PASSWORD3": "",
        "YOOKASSA_SHOP_ID": "",
        "YOOKASSA_SECRET_KEY": "",
    }
)
