import {
  observedPublicationFields,
  type ObservedPublicationMetric,
} from "@/lib/observed-publication-data";

export const observedPublicationMetricRequiredFields = [
  "metric_date",
  "source_code",
  "source_name",
  "profession_slug",
  "profession_name_ru",
  "seniority",
  "region_code",
  "region_name_ru",
  "salary_tax_status",
  "normalized_currency",
  "publication_count",
  "salary_disclosed_count",
  "salary_coverage",
  "midpoint_sample_size",
  "salary_median",
  "salary_average",
  "salary_p25",
  "salary_p75",
  "lower_bound_median",
  "upper_bound_median",
  "confidence_level",
  "remote_count",
  "remote_share",
  "last_ingested_at",
  "materialized_at",
  "transform_version",
  "current_market_claim",
] as const satisfies readonly (keyof ObservedPublicationMetric)[];

const nullableSalary = { type: ["number", "null"] } as const;

export function buildObservedPublicationDatasetSchema(siteUrl: string) {
  const base = siteUrl.replace(/\/$/, "");
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `${base}/open-data-daily.schema.json`,
    title: "TechRole Index observed publication daily dataset",
    description: "Contract for the public historical creation-date publication slices.",
    type: "object",
    additionalProperties: false,
    required: [
      "schema_version",
      "name",
      "description",
      "canonical_url",
      "data_layer",
      "metric_semantics",
      "current_market_claim",
      "language",
      "source",
      "date_from",
      "date_to",
      "date_modified",
      "transform_versions",
      "row_count",
      "publication_count",
      "normalized_currency",
      "salary_tax_status_dimension",
      "salary_minimum_sample",
      "caveat",
      "methodology_url",
      "provenance_url",
      "citation_url",
      "csv_url",
      "schema_url",
      "fields",
      "records",
    ],
    properties: {
      schema_version: { const: "1.0" },
      name: { type: "string", minLength: 1 },
      description: { type: "string", minLength: 1 },
      canonical_url: { type: "string", format: "uri" },
      data_layer: { const: "observed_historical" },
      metric_semantics: { const: "classified_publications_by_creation_date" },
      current_market_claim: { const: false },
      language: { const: "ru-RU" },
      source: {
        type: "object",
        additionalProperties: false,
        required: ["code", "name", "url"],
        properties: {
          code: { type: "string", minLength: 1 },
          name: { type: "string", minLength: 1 },
          url: { type: "string", format: "uri" },
        },
      },
      date_from: { type: ["string", "null"], format: "date" },
      date_to: { type: ["string", "null"], format: "date" },
      date_modified: { type: ["string", "null"], format: "date-time" },
      transform_versions: {
        type: "array",
        uniqueItems: true,
        items: { type: "string", minLength: 1 },
      },
      row_count: { type: "integer", minimum: 0 },
      publication_count: { type: "integer", minimum: 0 },
      normalized_currency: { const: "RUB" },
      salary_tax_status_dimension: {
        type: "array",
        minItems: 3,
        maxItems: 3,
        uniqueItems: true,
        items: { enum: ["gross", "net", "unknown"] },
      },
      salary_minimum_sample: { type: "integer", minimum: 3 },
      caveat: { type: "string", minLength: 1 },
      methodology_url: { type: "string", format: "uri" },
      provenance_url: { type: "string", format: "uri" },
      citation_url: { type: "string", format: "uri" },
      csv_url: { type: "string", format: "uri" },
      schema_url: { const: `${base}/open-data-daily.schema.json` },
      fields: {
        type: "array",
        minItems: observedPublicationMetricRequiredFields.length,
        maxItems: observedPublicationMetricRequiredFields.length,
        uniqueItems: true,
        prefixItems: observedPublicationFields.map((field) => ({
          type: "object",
          additionalProperties: false,
          required: ["name", "description"],
          properties: {
            name: { const: field.name },
            description: { const: field.description },
          },
        })),
        items: false,
      },
      records: {
        type: "array",
        items: { $ref: "#/$defs/observedPublicationMetric" },
      },
    },
    $defs: {
      observedPublicationMetric: {
        type: "object",
        additionalProperties: false,
        required: observedPublicationMetricRequiredFields,
        properties: {
          metric_date: { type: "string", format: "date" },
          source_code: { type: "string", minLength: 1 },
          source_name: { type: "string", minLength: 1 },
          profession_slug: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
          profession_name_ru: { type: "string", minLength: 1 },
          seniority: { enum: ["junior", "middle", "senior", "unknown"] },
          region_code: { type: "string", minLength: 1 },
          region_name_ru: { type: "string", minLength: 1 },
          salary_tax_status: { enum: ["gross", "net", "unknown"] },
          normalized_currency: { const: "RUB" },
          publication_count: { type: "integer", minimum: 0 },
          salary_disclosed_count: { type: "integer", minimum: 0 },
          salary_coverage: { type: "number", minimum: 0, maximum: 1 },
          midpoint_sample_size: { type: "integer", minimum: 0 },
          salary_median: nullableSalary,
          salary_average: nullableSalary,
          salary_p25: nullableSalary,
          salary_p75: nullableSalary,
          lower_bound_median: nullableSalary,
          upper_bound_median: nullableSalary,
          confidence_level: { enum: ["insufficient", "low", "medium", "high"] },
          remote_count: { type: "integer", minimum: 0 },
          remote_share: { type: "number", minimum: 0, maximum: 1 },
          last_ingested_at: { type: "string", format: "date-time" },
          materialized_at: { type: "string", format: "date-time" },
          transform_version: { type: "string", minLength: 1 },
          current_market_claim: { const: false },
        },
      },
    },
  } as const;
}
